### ISSUE TITLE
[ BUG ] NullReferenceException on LavaPlayer.PlayAsync(Action<PlayArgs> playArgsAction)

### ISSUE THREAD

**Issue by RofLBotZ94** [Yucked/Victoria#103]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

This method always throws NullReferenceException.

![Screenshot_5](https://user-images.githubusercontent.com/45794321/132084836-8c07a5ed-d61e-4f0f-ba65-8bfa337a137e.png)

This is due to the fact that `PlayArgs` is a `struct` and not a `class`, which means that when the `playArgs` object gets passed to the `Action` delegate it's done by value and not by reference, thus it does not modify the `playArgs` object outside of its scope.

The easiest solution would be to promote `PlayArgs` to a `class`. Another way to do it would be to create a custom delegate that accepts a `ref` parameter and replace the `Action` parameter with it. I'll provide some screenshots below to show you how I did it and I could make a PR with the change if you'd like.

![Screenshot_29](https://user-images.githubusercontent.com/45794321/132085561-c0b722fa-ca0b-4153-aaf6-8a7bb106e20b.png)

^Custom delegate

![Screenshot_33](https://user-images.githubusercontent.com/45794321/132085570-5af43e7e-28be-4b6e-a30a-6019c3c96e3b.png)

^Replacing `Action` parameter with the custom delegate and passing the `playArgs` object as a reference.

![Screenshot_36](https://user-images.githubusercontent.com/45794321/132085618-0d0f163f-de25-466a-a066-c5ad315c2dc4.png)

^This might be the biggest issue with the solution in case the user wants to use a lambda, as due to the `ref` keyword, it's not allowed to just specify the parameter of the lambda it's also required to specify the type of the parameter, which can make it kind of convoluted.

### `Stacktrace / Screenshots`

![Screenshot_12](https://user-images.githubusercontent.com/45794321/132085073-3cdff5fa-c6e6-4210-86fa-8922f2dce537.png)

^Passing the lambda to set the `PlayArgs` object. 

![Screenshot_11](https://user-images.githubusercontent.com/45794321/132085081-7c0d4822-f570-4073-9bbd-2e65489b5685.png)

^But as you can see, after calling the `Action`'s invoke method with the `playArgs` object as its argument, the object still remains "empty".

**Comment by Yucked** [comment]
I noticed that a while back but forgot to push a fix out. Thank you for reminding me! The best solution would be to declare it as a class.
