### ISSUE TITLE
[ BUG ] Using lavaNode.ConnectAsync() in the ShardReady event throws an InvalidOperationException

### ISSUE THREAD

**Issue by GabiRP** [Yucked/Victoria#105]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

When using lavaNode.ConnectAsync() on the ShardReady event throws an error: System.InvalidOperationException: _socketClient is not in ready state.

### `Stacktrace / Screenshots`

Code:
```cs
        public async virtual Task ShardReadyAsync(DiscordSocketClient shard)
        {
            Log.Info("Sharding", $"Shard {shard.ShardId} ready! Guilds:{shard.Guilds.Count} Users:{shard.Guilds.Sum(x => x.MemberCount)}");
            
            try
            {
                
                await _lavaNode.ConnectAsync();
                Log.Info("LavaLink", $"Lavalink connected for shard {shard.ShardId}");
            }
            catch (Exception e)
            {
                Log.Error("LavaLink", $"Error:\n{e}", e);
            }
        }
```

**Comment by Yucked** [comment]
The error is self explanatory. Your discord client hasn't reached ready state.

**Comment by GabiRP** [comment]
As it says in the readme.md, `In your DiscordSocketClient or DiscordShardedClient Ready event call _instanceOfLavaNode.ConnectAsync();`

Since there is no Ready event in DiscordShardedClient, i thought ShardReady was ok. What event should i use if ShardReady doesn't mean the discord client hasn't reached ready state?

**Comment by Yucked** [comment]
You will have to wait till all your shards are ready I believe

**Comment by GabiRP** [comment]
Yup, it was that, i just tried and it worked, thank u!

**Comment by Yucked** [comment]
Enjoy!
