### ISSUE TITLE
[ BUG ] Cannot apply indexing with [] to an expression of type 'IReadOnlyCollection<LavaTrack>'

### ISSUE THREAD

**Issue by Moonbase2004** [Yucked/Victoria#110]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

When trying to get the tracks from 'searchResponse', I cannot access the contents of the list.

### `Stacktrace / Screenshots`

*When debugging yourself, you can attach screenshots of Autos/Locals tabs in Visual Studio.*

**Comment by Yucked** [comment]
You can Google that error. It's not Victoria related.
