### ISSUE TITLE
[ BUG ] SearchAsync requires a SearchType parameter

### ISSUE THREAD

**Issue by jaydenfrn** [Yucked/Victoria#111]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

LavaNode SearchAsync method requires a SearchType parameter when the documentation says otherwise. Is the method supposed to require a SearchType even though the method is supposed to search through all SearchTypes?

### `Stacktrace / Screenshots`

![searchasync](https://user-images.githubusercontent.com/80577231/134803315-58503be7-1e22-44eb-a775-2a224f04c501.png)

**Comment by Yucked** [comment]
https://github.com/Yucked/Victoria/wiki/🔮-Changelog#-additions
