### ISSUE TITLE
Randomly started getting this error.

### ISSUE THREAD

**Issue by lunarleafy** [Yucked/Victoria#112]
My bot used to work fine. However, randomly I started getting this error message every time I would try to use a command. I even recoded the entire bot from scratch and got the same issue. I'm assuming it may have something to do with the Lavalink player itself but I'm not really sure..

console output
![image](https://user-images.githubusercontent.com/75377673/135593875-290c053d-85e8-41fb-95cd-f75dd5546667.png)
discord output
![image](https://user-images.githubusercontent.com/75377673/135593888-39238ba0-0404-4a0e-9d48-b037ae5f8b72.png)
lavalink output
![image](https://user-images.githubusercontent.com/75377673/135594227-a6694c96-0bf6-4af3-ac4a-212f0c3a6f5f.png)

**Comment by Yucked** [comment]
Lavalink doesn't show anything about an incoming request. That error means that Victoria isn't connected to Lavalink. Check if you're calling ConnectAsync in your Ready event.

**Comment by lunarleafy** [comment]
![image](https://user-images.githubusercontent.com/75377673/135769155-37f0683b-2e9c-4ca4-8c99-8b5355ce8327.png)
this is what ive had, i havent changed anything

**Comment by Yucked** [comment]
Then it should be opening a connection to Lavalink and Lavalink should be stating that as well. Are you subbed to your Ready event

**Comment by lunarleafy** [comment]
Hey, I just fixed it after recoding it for a 3rd time, I realized that by resetting the application.yml to default and resetting up my Lavalink I was able to actually get a connection from my bot to my Lavalink.jar.
