### ISSUE TITLE
Play/Skip Commands occasionally don't work

### ISSUE THREAD

**Issue by ghost** [Yucked/Victoria#113]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

*I have noticed that sometimes when my play/skip command is used, victoria loses its connection to LavaLink, but im not sure why as the commands work 99% of the time?*

### `Stacktrace / Screenshots`

*Here is a screenshot of the error when the play/skip command does not work:*
![Screenshot 2021-10-19 102934](https://user-images.githubusercontent.com/74121606/137819906-be27f81d-e6b4-4990-b3f8-746efb6481ee.png)
*Play command:*
![Screenshot 2021-10-19 103129](https://user-images.githubusercontent.com/74121606/137820028-61b7143b-f6ea-4c66-b9bb-980311dacc18.png)
*Skip command:*
![Screenshot 2021-10-19 103255](https://user-images.githubusercontent.com/74121606/137820133-5b04727e-d3b1-4302-95c1-0f23ee1cfa7e.png)

**Comment by Yucked** [comment]
what version

**Comment by ghost** [comment]
Victoria Version - 5.2.3
LavaLink Version - [Latest release](https://github.com/freyacodes/Lavalink/releases/tag/3.3.2.5)
Discord.Net Version - 2.4.0

**Comment by Yucked** [comment]
Fixed in a658212cf0d5c4d7faed75a817b581bd017b09c2
