### ISSUE TITLE
[ BUG ] LavaNode.IsConnected returns true

### ISSUE THREAD

**Issue by unwell35** [Yucked/Victoria#116]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

LavaNode.IsConnected is always returns true even if the lavalink is stopped

**Comment by Yucked** [comment]
Added additional checks where it may end up closing connections 0d9dc38394a7eb23023e55816d9c99d4dbfa2c2f
