### ISSUE TITLE
Skip throws exception[ BUG ]

### ISSUE THREAD

**Issue by nssa-dev** [Yucked/Victoria#117]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---
Issue

SkipAsync throws Victoria.LavaException when enqueuing and skips any track in playlist with Russian named songs. Manually added songs doesn't.

Screenshots
![Discord_FyUeib2ju5](https://user-images.githubusercontent.com/69722067/147378156-ba5e7396-af1a-4ed9-9cdc-26771fe09115.png)
Playlist with Russian named songs
![WindowsTerminal_nXCH4Id4ii](https://user-images.githubusercontent.com/69722067/147378265-e6dc2172-08ac-4588-b461-8800b9b41c77.png)

**Comment by Yucked** [comment]
That's Lavalink throwing an exception. Victoria can't do anything about it other than re-queue.
