### ISSUE TITLE
[ BUG ] LavaNode.SearchAsync() shouldn't select videos that are age restricted.

### ISSUE THREAD

**Issue by kloczewiak** [Yucked/Victoria#120]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

`LavaNode.SearchAsync()` shouldn't select songs that are age restricted, because this results in a `OnTrackException` when the track gets played.
Either this or add a `isPlayable` flag to `LavaTrack` so we can handle this before the track gets queued.

### `Stacktrace / Screenshots`

![image](https://user-images.githubusercontent.com/42269909/148849631-5bbb6090-5f99-4b6a-92de-3783eb2f2b62.png)
![image](https://user-images.githubusercontent.com/42269909/148849729-4716c06e-a2b7-4da9-accc-614189e519cc.png)

**Comment by Yucked** [comment]
Belongs there https://github.com/freyacodes/Lavalink
