### ISSUE TITLE
[ BUG ] can’t seem to load YouTube playlist?

### ISSUE THREAD

**Issue by TBooty** [Yucked/Victoria#122]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`
whenever a YouTube playlist is linked it will sanitize the input to a single YouTube video and only play that.

I was digging through some old pull requests and I noticed some one mentioned an option to set it to true or false. Is there an option i am missing in v5 to support playlists?

I dig through the documentation and the code and not seeing much besides, I could be missing it here

**Comment by Yucked** [comment]
Which PR are you referring to?

**Comment by TBooty** [comment]
> Which PR are you referring to?

I saw it here 

https://github.com/Yucked/Victoria/pull/36

But that was 2019 and it looks like the lava test client was deprecated

**Comment by Yucked** [comment]
No that is completely unrelated. What you are mentioning is a Lavalink issue. Victoria forwards the information the Lavalink and it's up to Lavalink/LavaPlayer to parse everything on their end.

**Comment by TBooty** [comment]
Sounds good. Will dive into lavalink to see how it returns. 

Thanks for your help
