### ISSUE TITLE
LyricsResolver Index out of bound

### ISSUE THREAD

**Issue by BlyZeDev** [Yucked/Victoria#123]
**Describe the bug**
Index was out of the bounds of the array error when I try to fetch lyrics.

**Expected behavior**
To get the lyrics from Genius and OVH.

**Screenshots**
![Screenshot 2022-01-19 170128](https://user-images.githubusercontent.com/95288041/150168663-0b5104bf-ba80-4713-8c91-d1fe7d306559.png)
![Screenshot 2022-01-19 170201](https://user-images.githubusercontent.com/95288041/150168658-6fcc398e-7bcc-4184-a515-4a983809de84.png)

**Comment by Yucked** [comment]
What song was it?

**Comment by BlyZeDev** [comment]
https://www.youtube.com/watch?v=aYKN5_b7yVo

**Comment by Yucked** [comment]
Is that song on Genius?

**Comment by BlyZeDev** [comment]
It is but its instrumental
https://genius.com/Camellia-flamewall-lyrics

**Comment by BlyZeDev** [comment]
So I need to catch that

**Comment by Yucked** [comment]
The parser cleans out the video title and checks whether the uploader name includes the artist name as well and matches that.

There is no way for it to know if:
Camellia Official [FREE DL] Flamewall [Symphonic Speed Metal] == Flamewall かめりあ (Camellia) == https://genius.com/Camellia-flamewall-lyrics

Please be mindful
