### ISSUE TITLE
[Bug]: Player state is playing yet tracking is not being processed

### ISSUE THREAD

**Issue by TBooty** [Yucked/Victoria#125]
### Describe your issue in as much detail as possible

I recently had to switch from .Net standard 6.0 to .netcore 3.1
So I downgraded victoria to V5.2.3

I noticed that my songs no longer play from the player.
If I debug it, I can see that the player exists, it has a queue of 1 and has a track loaded the status is set to playing but the position of the track remains 0:0:0

If I check my discord bot logs I can see it getting updates about the track from lavalink
![image](https://user-images.githubusercontent.com/16490252/152284876-52713717-b759-41b2-a1b1-40f4ddb917af.png)
I can see the commands fire off in lavalink for the play 
![image](https://user-images.githubusercontent.com/16490252/152286370-6541abcb-342f-42b0-9fef-8a34f2e07a92.png)

However anytime I track the track updated events arg the track position will remain 0
![image](https://user-images.githubusercontent.com/16490252/152285822-1ff1390a-0143-4e2a-9981-7841b398ea2d.png)

### Version

v5 (Latest)

### Version

GitHub's latest

**Comment by TBooty** [comment]
Diving into this more I noticed when it joins a channel it throws an error and dies and restarts the connection
![image](https://user-images.githubusercontent.com/16490252/152287759-21bfc1ab-ece0-4c5f-b9d8-00b88060e400.png)
I haven't changed lavalink at all, just downgraded my .net version and the version of victoria.

Not sure why it disconnects as soon as it joins the voice channel


So it seems the issue stems from it being disconnected from the voice channel after a join,

If I put lavalink in debug mode it I can see some web socket exceptions of:
` PooledUnsafeDirectByteBuf(ridx: 0, widx: 48, cap: 2048)) that reached at the tail of the pipeline. Please check your pipeline configuration.`


So not sure what the difference between my .net version of .net standard 6.0  and the victoria 5.2.5.,, but downgrading seems to have broken the join some how

**Comment by Yucked** [comment]
Downgraded from Netstandard6.0 to Net Core 3.1? Why? 

Can you put Lavalink and victors in debug mode and see if they are actually the track update position? 

the second issue is completely unrelated. What .Net framework you use doesn’t matter to Lavalink. You need to use latest version of Lavalink since you’re using a last version of Lavalink which deprecated shards count for client header.

**Comment by TBooty** [comment]
> Downgraded from Netstandard6.0 to Net Core 3.1? Why?
> 
> Can you put Lavalink and victors in debug mode and see if they are actually the track update position?
> 
> the second issue is completely unrelated. What .Net framework you use doesn’t matter to Lavalink. You need to use latest version of Lavalink since you’re using a last version of Lavalink which deprecated shards count for client header.

How do I put Victora into debug mode?
Lavalink seems to be chugging along and says decoding websocket frames

**Comment by Yucked** [comment]
Set log severity to debug in lavaconfig and use the OnLog event in Lavanode

**Comment by TBooty** [comment]
![image](https://user-images.githubusercontent.com/16490252/152446366-f877bd3a-f031-4b66-a902-757e1355ddad.png)

The position doesn't seem to update

![image](https://user-images.githubusercontent.com/16490252/152446549-dc6395a3-bd02-4031-9bbd-c7d9f8d82274.png)

**Comment by Yucked** [comment]
Then Lavalink isn’t sending it

**Comment by TBooty** [comment]
![image](https://user-images.githubusercontent.com/16490252/152446847-bc12925d-ca13-422f-b2b4-d05172877d78.png)
not too familiar on the lavalink side, but it seems to be sending the events, the song will end it will initiate the auto disconnect but the player never advances

I had a working setup before I downgraded by .net version and my version of victoria. 

(I downgraded due to slash commands not registering in a docker container)

**Comment by Yucked** [comment]
It can send the events but still not send the position update data that is needed. Does it happen for all tracks?

**Comment by TBooty** [comment]
Yeah happens for every video I queue up. I can’t seem to get a single one to track

**Comment by TBooty** [comment]
If I change my .net version back to .net 6.0 and victoria 5.25 it works just fine...

As soon as I step down to that previous version of victoria it no longer works

**Comment by Yucked** [comment]
The only thing I can think of is that it referencing the wrong System.Text.Json library in .netcore3.0

**Comment by TBooty** [comment]
No worries, I think it may be easier to just swap back to what is working and chase down my other issue with docker.


Thank you for your help on this.
