### ISSUE TITLE
[Bug]: Expected end of string, but instead reached end of data. 

### ISSUE THREAD

**Issue by TheMeq** [Yucked/Victoria#130]
### Describe your issue in as much detail as possible

Sometimes, I get the following error message using Victoria (5.2.8) from NuGet.

``Expected end of string, but instead reached end of data. LineNumber: 0 | BytePositionInLine: 512.`` 

This completely stops playback and I can't see a way to catch/recover from this error message without restarting the bot and manually playing another track. 

This is fired after Lavalink reports FINISHED/TrackEndEvent but before the event in Victoria for TrackEndEvent is called (I think).

### Version

v5 (Latest)

### Version

GitHub's latest

### Relevant log output

```shell
DBUG [VICTR] {"op":"playerUpdate","state":{"connected":true,"position":194800,"time":1653745486599},"guildId":"937118217661476925"}
DBUG [VICTR] {"playingPlayers":1,"op":"stats","memory":{"reservable":4294967296,"used":608143008,"free":92305760,"allocated":700448768},"frameStats":{"sent":3000,"deficit":0,"nulled":0},"players":1,"cpu":{"cores":6,"systemLoad":0.005641666666666666,"lavalinkLoad":0.002907848691884686},"uptime":48888050}
DBUG [VICTR] {"op":"playerUpdate","state":{"connected":true,"position":199760,"time":1653745491618},"guildId":"937118217661476925"}
DBUG [VICTR] {"op":"playerUpdate","state":{"connected":true,"position":204760,"time":1653745496605},"guildId":"937118217661476925"}
EROR [VICTR] Expected end of string, but instead reached end of data. LineNumber: 0 | BytePositionInLine: 512.
DBUG [VICTR] {"op":"event","reason":"FINISHED","type":"TrackEndEvent","track":"QAABWQIARUZhcnJ1a28sIFZpY3RvciBDYXJkZW5hcywgRGogQWRvbmkgLSBFbCBJbmNvbXByZW5kaWRvIChGUkVFQk9UIFJFTUlYKQAPRlJFRUJPVCB8IEV4dHJhAAAAAAADKusAck86aHR0cHM6Ly9hcGktdjIuc291bmRjbG91ZC5jb20vbWVkaWEvc291bmRjbG91ZDp0cmFja3M6MTE2NjI2MDA1Ny80ZGYyODU2ZC03MjYwLTQ3OTctODQ1Ni05NjgzOTRhN2ZkOGEvc3RyZWFtL2hscwABAGxodHRwczovL3NvdW5kY2xvdWQuY29tL2ZyZWVib3RyZW1peGVzYW5kbW9yZS9mYXJydWtvLXZpY3Rvci1jYXJkZW5hcy1kai1hZG9uaS1lbC1pbmNvbXByZW5kaWRvLWZyZWVib3QtcmVtaXgACnNvdW
```

**Comment by Yucked** [comment]
That's a long track hash which seems to be not fitting in the default buffer size of websocket. Increase the websocket buffer to twice the length and it should fix it.

**Comment by TheMeq** [comment]
Thanks, will give it a whirl and i'll report back if any further issues. Many Thanks.

**Comment by v0fbu1vm** [comment]
> That's a long track hash which seems to be not fitting in the default buffer size of websocket. Increase the websocket buffer to twice the length and it should fix it.

How do I change the buffer size of websocket?

**Comment by Yucked** [comment]
Can be changed in NodeConfiguration#SocketConfiguration

**Comment by v0fbu1vm** [comment]
> Can be changed in NodeConfiguration#SocketConfiguration

I was able to figure that out with the help of ChatGPT, although the problem isn't fixed yet! I just issued a bug regarding a similar issue. It can be found here https://github.com/Yucked/Victoria/issues/145
