### ISSUE TITLE
[Bug]: Equalizer does not propagate updates?

### ISSUE THREAD

**Issue by ivanbiljan** [Yucked/Victoria#135]
### Describe your issue in as much detail as possible

I'm using the equalizer as a bass booster. Boosting works fine, however resetting a boosted stream does not. See image below:
![image](https://user-images.githubusercontent.com/7541476/196808611-fe259489-205b-4c55-8e89-03bf4c3483a8.png)

Setting the boost to `BassBoost.High` produces expected results with audios such as https://www.youtube.com/watch?v=ft5X5wVBcYQ&ab_channel=UltimateBassBooster, i.e. ,there's a noticeable difference in the strength of the bass.

However, if I try to revert to original state by setting the boost to `None` (0 gain) nothing happens

### Version

v5 (Latest)

### Version

GitHub's latest

**Comment by Yucked** [comment]
Unsure if it gets ignored because 0.0 is default value. Try -0.1 and see if that works

**Comment by ivanbiljan** [comment]
Right, I saw the JsonIgnore, however I forgot to mention that I tried going from -0.25 to 0.35 and that didn't work either unfortunately

**Comment by ivanbiljan** [comment]
For whatever it's worth I just tested this against the `v6` branch and it seems to work as intended

**Comment by Yucked** [comment]
If it's working on v6 then it's all good. v5 won't be maintained anymore
