### ISSUE TITLE
[ BUG ] .PlayAsync with PlayArgs always throws NullReferenceException

### ISSUE THREAD

**Issue by XDeveluxe** [Yucked/Victoria#137]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

When trying to use .PlayAsync with Args - its always throws NullException.

### `Stacktrace / Screenshots`
![image](https://user-images.githubusercontent.com/102395107/204487895-610e74f1-82dc-4d86-ada1-5f94e86de700.png)

**Comment by stackwalking** [comment]
That's not how you use delegates, but regardless this function will still throw argument null exception, [pr138](https://github.com/Yucked/Victoria/pull/138) this pr fixes track and all the other params being null
