### ISSUE TITLE
[ BUG ] Some video make Victoria throw a silent exception, making all event not tigger anymore

### ISSUE THREAD

**Issue by AlexandreBazeaud** [Yucked/Victoria#140]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`
Exception is produced at LavaNode.cs line 363, the data received contain unparsable json. When this silent exception is thrown (because JsonDocument.Parse is not in the try catch) any event going forwards will not be handled at all, forcing a restart of the all application.

### `Stacktrace / Screenshots`
![image](https://user-images.githubusercontent.com/63203499/214284793-27f09416-7f7c-4cff-b804-767a6662ffe8.png)

### `Solution`
The bug seems to be reproducable 100% using this link https://www.youtube.com/watch?v=Ksl04qNkkRM, encodedTrack is too big and bufferSize is too small, causing the Json received to miss mandatory characters to be parsable, the solution is to increase BufferSize

**Comment by Yucked** [comment]
fixed in recent commit
