### ISSUE TITLE
Can no longer add the lava node to IServiceCollection

### ISSUE THREAD

**Issue by ClaudiuHBann** [Yucked/Victoria#150]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

After updating to the last version of Victoria and no code changes in the code below, now it crashes:
![image](https://github.com/Yucked/Victoria/assets/78564392/5f5283fc-6d68-40be-bf32-facd2919974a)

### `Stacktrace / Screenshots`

![image](https://github.com/Yucked/Victoria/assets/78564392/a0414bb3-aaa8-4f09-9c3a-b9d5666f17c3)
![image](https://github.com/Yucked/Victoria/assets/78564392/e1d0eb42-dbe1-40e7-97f3-f11180c5891a)
![image](https://github.com/Yucked/Victoria/assets/78564392/9fe925bf-a00e-4fda-9628-6fe5a9115e8f)
![image](https://github.com/Yucked/Victoria/assets/78564392/c89b8339-69fa-4066-8eb5-36b2be7222e0)

**Comment by Yucked** [comment]
What version is this?

**Comment by ClaudiuHBann** [comment]
The last version from nugget, I think it's 6.0.14

**Comment by ClaudiuHBann** [comment]
> What version is this?

Last nuget version which is [6.0.1026](https://www.nuget.org/packages/Victoria/6.0.1026)
And I am using Lavalink [4.0.0-beta.4](https://github.com/lavalink-devs/Lavalink/releases/tag/4.0.0-beta.4)

**Comment by Yucked** [comment]
Victoria 6.x doesn't support Lavalink 4.x or 3.7 and above, only v7 will have support for 3.7 and above
