### ISSUE TITLE
[ BUG ] Victoria sending blank or slightly wrong payloads for the Stop and Resume functions to work expectedly

### ISSUE THREAD

**Issue by ManiacalSheep** [Yucked/Victoria#154]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

Have a bot and try to stop a current track or resume a paused one

### `Stacktrace / Screenshots`

Victoria is sending blank or slightly wrong payloads for the Stop and Resume functions to work expectedly

**Comment by Yucked** [comment]
Fixed in #156 

Thank you
