### ISSUE TITLE
Suggestion: Make all folders not be a namespace provider

### ISSUE THREAD

**Issue by TheMulti0** [Yucked/Victoria#27]
So I love namespaces, and you've arranged the folder structure perfectly in your library, but I think that when designing a library, you should keep in mind that the user prefers not to import many different namespaces.
And since you have about 2 folders deep (ex: `Victoria.Entities.Enums`) I think disabling namespace provider on each folder- aka putting all classes at the `Victoria` root namespace without changing the folder scheme would be great.

**Comment by Yucked** [comment]
I'm not sure about that. It just looks like bad design and I'm sure everyone would agree with that. The only namespace I do wanna change is `Victoria.Entities.Responses` since it almost all the entities in Entities folder are responses, so I might move entities in Responses to root Entities.

**Comment by TheMulti0** [comment]
@Yucked Newtonsoft Json for example has most classes in the same namespaces.
Same does Microsoft ASP.NET libs, log4net and any major libs because it's a hassle to import multiple namespaces for one functionality.

**Comment by Yucked** [comment]
I moved all sub-entities in entities folder. Shouldn't have to import Entities.Enums / Entities.Responses.
Closing this issue now.

**Comment by TheMulti0** [comment]
@Yucked Hey there. I'd like to re-open this suggestion for v5, and I'll shortly remind why did I firstly want to do this.
An API should have as much as imports involved for the consumer per project, because it is a hassle to import many different namespaces like; Victoria.Entities, Victoria.Helpers.
I do appreciate that the main classes are all in the root folder, but I think all classes in an API should have the root namespace, makes it a much shorter import.

**Comment by Yucked** [comment]
You should post that in #40

**Comment by TheMulti0** [comment]
> You should post that in #40

I was going to, but then I thought it may not be that much architectural as the discussion there. I'll re-post there.
