### ISSUE TITLE
LavaNode.TrackUpdate nullifies track during TrackReason.Replaced

### ISSUE THREAD

**Issue by trigger-death** [Yucked/Victoria#3]
At the moment it's imposible to skip a song correctly because when a song is skipped, the `TrackReason.Replaced` Finished event is triggered and `LavaNode.TrackUpdate` nullifies the new track you assigned. Internally the playback works. But anything that relies on `LavaPlayer.CurrentTrack` is now broken.

**I suggest the following change:**
```cs
private void TrackUpdate(TrackFinishData data)
{
    if (data.Reason != TrackReason.Replaced)
        data.LavaPlayer.CurrentTrack = null;
    Finished?.Invoke(data.LavaPlayer, data.Track, data.Reason);
}
```

**Comment by Yucked** [comment]
Hm, would it be better to do something like:
```cs
private void TrackUpdate(TrackFinishData data)
{
    data.LavaPlayer.CurrentTrack = data.Track;
    Finished?.Invoke(data.LavaPlayer, data.Track, data.Reason);
}```

**Comment by trigger-death** [comment]
Actually yeah that sounds good. Didn't even occur to me.

**Comment by Yucked** [comment]
Those changes have been implemented. Lemme know how it goes for you and close this issue if it works out.

**Comment by Yucked** [comment]
During recent update I've changed the whole method:
```cs
        private void TrackUpdateInformation(ulong guildId, TrackReason reason, LavaTrack track)
        {
            _lavalink.LogDebug("Received track update.");
            if (!_players.TryGetValue(guildId, out var old)) return;
            old.CurrentTrack = track;
            _players.TryUpdate(guildId, old, old);
            Finished?.Invoke(old, track, reason);
        }
```

Hopefully that fixed the issues you were having. I'm now gonna be closing this issue.
