### ISSUE TITLE
[ Feature Request ] voice channel connection options in configuration

### ISSUE THREAD

**Issue by Earu** [Yucked/Victoria#31]
It would be interesting to have options in the configuration object like:

- InactivityMaxTime (TimeSpan) which would refer to how long the connection to a voice channel should be maintained when the bot is not playing anything.
- DisconnectWhenInactive (bool) which would refer to whether or not the connection should be dropped when we are not playing anything.
- DisconnectWhenEmpty (bool) which would refer to whether or not a connection to a voice chat should be dropped when the voice channel is populated only by bots or is empty.

**Comment by Yucked** [comment]
Implemented.
