### ISSUE TITLE
[ BUG ] SetVolumeAsync after SkipAsync (can) throw(s) InvalidOperationException

### ISSUE THREAD

**Issue by emre1702** [Yucked/Victoria#32]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

If you try to set the volume with LavaPlayer.SetVolumeAsync after skipping the current track with SkipAsync, you can get an exception:
> This operation is invalid since player isn't actually playing anything.

I get this problem in Discord.Net commands using your Prototype bot.
Only added a SetVolume command and it normally works fine, but after using the skip command it can't use SetVolumeAsync anymore.
Tried to use SetVolumeAsync right after skipping the track and it worked. Also tried to use LavaSocketClient.GetPlayer and SetVolumeAsync with the returned player right after skipping the track, it worked again.
It's only not working in another command.

player.CurrentTrack isn't empty, the "NowPlaying" command works perfectly.

### `Stacktrace / Screenshots`

> at Victoria.LavaPlayer.SetVolumeAsync(Int32 volume)
   at BonusBot.AudioModule.SetVolume(Int32 volume) in [MyPath]
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)

**Comment by emre1702** [comment]
Downloaded the source code and went through with the debugger.
The bug happens because of the TrackEnd event:
https://github.com/Yucked/Victoria/blob/v4/LavaBaseClient.cs#L255

Here IsPlaying is set to false.

**Comment by emre1702** [comment]
And the easy solution should be to change from:
```csharp
player.IsPlaying = false;
if (endReason != TrackEndReason.Replaced)
    player.CurrentTrack = default;
```
to 
```csharp 
if (endReason != TrackEndReason.Replaced) 
{
    player.CurrentTrack = default;
    player.IsPlaying = false;
}
```

**Comment by Yucked** [comment]
That fix doesn't make sense. When OnFinished event is fired that means player is not playing anything at all which is why it should be false regardless of if the track is replaced.

**Comment by emre1702** [comment]
If you skip a track, the previous track is finished.

Maybe it would make more sense if there was a TrackStart event where IsPlaying gets set to true (instead of instantly setting IsPlaying to true at SkipAsync).

**Comment by Yucked** [comment]
When you skip a track the previous track is replaced. And, all events are what lavalink emits. There is only a single custom event which is `Log`. When you call `SkipAsync` it calls `PlayAsync` internally which sets `IsPlaying` to true. Now, I'm unsure if that may be getting overridden by the OnTrackFinished event for which you opened the PR for. I guess your PR does make sense now that I think about it more.

**Comment by emre1702** [comment]
And because the events comes a bit later (from WebSocket), I could use SetVolumeAsync right after using SkipAsync, but not later in another command.
Is solved now.
