### ISSUE TITLE
LavaPlayer.Stop disposes of player, documentation labels it as a "Skip" feature

### ISSUE THREAD

**Issue by trigger-death** [Yucked/Victoria#4]
So, it seems that either the documentation or functionality of `LavaPlayer.Stop()` is incorrect because once you call stop, the player is disposed of and can no longer be used.

Assuming it is supposed to end the current song to allow the next to play, then just removing `Volatile.Write(ref IsDisposed, true);` should do the trick:
```cs
public void Stop()
{
    if (!IsConnected)
        throw new InvalidOperationException("This player isn't connected.");
    // v Remove this line v
    Volatile.Write(ref IsDisposed, true);
    CurrentTrack = null;
    _lavaSocket.SendPayload(new StopPayload(Guild.Id));
}
```

**Comment by Yucked** [comment]
Player can still be used and stop doesn't dispose of the whole player object and player object is not disposable, it just changes the `IsConnected` to true/false which is read via `Volatile.Read(ref isDisposed)` and yes it can be used for both skipping and stopping.

**Comment by trigger-death** [comment]
But how do you reconnect the player to continue the queue? `IsDisposed` is only set to true in the constructor, so any chance to interact with the player will throw `InvalidOperationException` for not being connected.

**Comment by Daniele122898** [comment]
Im having the same issue. after the stop you cannot use any other commands. It will throw the exception and say its not connecting. Using the join command will say it connected but still throw the same errors. Its essentially useless after calling stop and the entire bot needs to be restarted otherwise he wont leave the channel

**Comment by trigger-death** [comment]
I think the voice channel connection is *partly* a Discord.Net issue. It seems even calling `IVoiceChannel.DisconnectAsync()` does nothing after a bot restart while still in voice. As a workaround in the meantime:
```cs
IAudioClient audioClient = await channel.ConnectAsync().ConfigureAwait(false);
await Task.Delay(100).ConfigureAwait(false); // Some arbitrary amount of time, so the disconnect succeeds.
await audioClient.StopAsync().ConfigureAwait(false);
player = await node.JoinAsync(channel).ConfigureAwait(false);
```

**Comment by Yucked** [comment]
So this problem should be fixed now. If you call play after calling stop it will work and no longer check if `IsConnected` is true and left up to user if they want to add it to their Play commands. Please let me know if this issue is solved or not and if it is feel free to close this issue.
