### ISSUE TITLE
[ PROPOSAL ] v5 Feedback and Discussion

### ISSUE THREAD

**Issue by Yucked** [Yucked/Victoria#40]
<p align="center">
<img src="https://media.giphy.com/media/2sYKSgbdkXvrpn7eBN/giphy.gif" width="40%"/>
</p>

---

### `Proposal Description:`

I'm adding everything in a single project instead of creating 4 different packages for each thing. The original idea was to have 4 projects like so:

- `Victoria.Commons`: Contains base classes that will be utilized by Frostbyte and Lavalink.
- `Victoria.Addons`: Addons like LyricsHelper/ThumbnailHelper will be here. Along with other lyric scrappers.
- `Victoria.Frostbyte`: Will depend on `Commons` and have classes like `FrostClient`, `FrostPlayer`, etc.
- `Victoria.Lavalink` Follows Frostbyte design pattern.

Then push an additional package called `Victoria` that contains all the packages above but then I realized why not just keep it a single project. Makes everything easier.

Now that I've pushed the first [`commit`](https://github.com/Yucked/Victoria/commit/d5edc28c8941ae5d1855b93d4ab73329a79d155d) I wanted to know what kind of design do you've in mind and what things would you like changed, etc before I start writing concrete implementation of base classes.

**Comment by DraxCodes** [comment]
Personally I think the multiple package idea would be better instead of just the one. I can already imagine situations where I wouldn't need to use Addons. I also feel like having both the Frostbyte and Lavalink in the same package is a tad redudant, why would I want to use both? Surely I'd just download the one that I want, whether that be Frostbyte or LavaLink 

Just some thoughts. Keep up the good work though matey!

**Comment by TheMulti0** [comment]
I like the idea of separating the packages, though I did not understand what did you mean by 'keeping it a single project', because seperating into multiple packages is impossible without seperating into different projects.
I'm not sure that having an additional package called Victoria that contains them all is a good idea, it might confuse people which will try installing both Victoria and the other package they need (Victoria.Lavalink / Frostbyte / Addons).

**Comment by Yucked** [comment]
It will similar to how D.NET, if you install D.NET it installs all the other packages and it will similarly. I'll be breaking the project into several separate projects.

**Comment by TheMulti0** [comment]
I think that when designing a library, you should keep in mind that the user prefers not to import many different namespaces.
I like the folder scheme in Victoria, but I think that APIs should only have one namespace per project or package, meaning that all classes in Victoria.Frostbyte will be organized in folders, but their namespace will be the root namespace; Victoria.Frostbyte.

**Comment by Yucked** [comment]
Since the new version isn't done I will be keeping the namespaces like so. If I see a user has to import a lot of namespaces then I'll definitely move entities and sub-dirs in entities to just entities otherwise user won't be importing much.

**Comment by TheMulti0** [comment]
> 
> 
> Since the new version isn't done I will be keeping the namespaces like so. If I see a user has to import a lot of namespaces then I'll definitely move entities and sub-dirs in entities to just entities otherwise user won't be importing much.

I still think that you should use the root namespace, but it's better than nothing.

**Comment by ChrisVDB36** [comment]
I hope im on the right side here (still new in using github tho i already have an account for a while :P)
But I am using your Victoria package to play music on my personal discord bot, however, i would like to show a text in my chat with all information and for that I also want to show the requester's name, but there is no extra property available in the LavaTrack for that, could it be a possibility to add this extra property in LavaTrack (as string) please?
Im fairly new to C#, still struggling a lot (currently a student on a course for C#) and when I am trying to make a class that inherits from LavaTrack, I somehow cant keep track on who requested which song and i keep getting null refferences or dead ends and the music wont even play and I think I am just using this inheritance wrong

I have 2 places where I tell my discord members which song is going to play
1: when you use the play command it will say 'now playing or enqueue this song, requested by this user'
2: when the next song comes up it also says this information 'now playing this song, requested by this user'
But this is not working and i think an extra property build in in LavaTrack will make this way easier, if possible that is

I hope my problem a.k.a suggestion is written properly enough to understand, thanks for reading
have a nice day

**Comment by TheMulti0** [comment]
@ChrisVDB36 There is no need for inheritance. The easiest solution is to have a custom queue which is some kind of dictionary of LavaTrack, Member that requested the command, that way when the some LavaTrack is playing, you can match its requester.

**Comment by ChrisVDB36** [comment]
> @ChrisVDB36 There is no need for inheritance. The easiest solution is to have a custom queue which is some kind of dictionary of LavaTrack, Member that requested the command, that way when the some LavaTrack is playing, you can match its requester.

Thanks for your fast answer, thought I gotta admit I am not so good yet on that area (queue's) but I will try it out and see how far I can get this done, thanks again have a nice day
