### ISSUE TITLE
[ BUG ] No payloads from LL after a while

### ISSUE THREAD

**Issue by Earu** [Yucked/Victoria#41]
After a while, apparently mostly after using SoundCloud tracks, Victoria does not receive anymore payloads from Lavalink. I tried using `LogSeverity.Debug` which bypasses the `Players.TryGetValue` check, and nothing gets logged so the problem comes from something else than a threading issue. It could be the `SocketHelper` class or Lavalink itself, although the later seems unlikely considering I've found no similar issue among other wrappers.

This is on the V4 version of Victoria.

**Comment by Earu** [comment]
Possible relevant issue: https://github.com/Frederikam/Lavalink/issues/177

**Comment by Yucked** [comment]
Probably fixed in v5 with resuming support.
