### ISSUE TITLE
Editing Victoria...

### ISSUE THREAD

**Issue by ChrisVDB36** [Yucked/Victoria#47]
Are we allowed to download, edit & recompile Victoria??
I would like to edit a few things on this but only if allowed.

Thanks in advance

**Comment by Yucked** [comment]
It's under MIT broski, go nutsi. Just make sure you give credit where its due since many people worked on it.

**Comment by ChrisVDB36** [comment]
> It's under MIT broski, go nutsi. Just make sure you give credit where its due since many people worked on it.

Im still kinda newish to all this github stuff ;p thats why I asked.
Now I just need to figure all this out, still in a learning branching on C#, I assume this is compiled in VS 2019 as in my 2017 a lot of errors pop up.

Thanks for your response

**Comment by Yucked** [comment]
Version 5 is in 2019 targets net core 3.0 prev 6. Since you're new to github you can fork it or download it and clone it to your desktop.

**Comment by ChrisVDB36** [comment]
I see, will try that out this weekend.
Thanks a lot for all the information, have a nice day
