### ISSUE TITLE
[ BUG ] Playing music via YouTube url's stopped working since this morning

### ISSUE THREAD

**Issue by ChrisVDB36** [Yucked/Victoria#48]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

Everything was working fine up until this morning where a user in my discord reported the bot been broken when looking up youtube urls...
Everything still works for other services such as for example: soundcloud

I tried many different things to come to the point where I believe this problem cannot be fixed on my side but has something to do with Victoria trying to load in youtube information and failing to do so. (thats just a guess at this moment, not pointing fingers)

Can you please look into this, I also uploaded my log file with the latest log when I tested it myself.
Thanks in advance

### `Stacktrace / Screenshots`

[log.txt](https://github.com/Yucked/Victoria/files/3445551/log.txt)

**Comment by Yucked** [comment]
The recent issues on Lavaplayer: https://github.com/sedmelluq/lavaplayer/issues

Nothing to do with Victoria

**Comment by ChrisVDB36** [comment]
Okidoki, reporting the issue there, sorry for the time waste
Have a nice day

**Comment by Yucked** [comment]
No worries fam squad. Closing this issue now.

**Comment by ChrisVDB36** [comment]
Hey, some guy told me there that it was an issue with LavaPlayer and it got updated to a newer version, do I need to do something to make this work now or can you fix this on your side? I am not sure what to do atm this is all still a learning process for me, sorry if i come over as spam im just trying to get this fixed, thanks in advance

Version 1.3.19 is out he said

**Comment by MCOfficer** [comment]
I wrote my explanation (the way i see it, corrections from actual experts welcome) over at sedmelluq/lavaplayer#200, the aforementioned issue.

**Comment by Yucked** [comment]
Victoria doesn't require any change on it's side unless Lavalink pushes out a new feature or introduces a breaking change. Once Lavalink implements the latest version of Lavaplayer, you'd have to download new version of Lavalink and everything should be good to go.

Lavaplayer in Victoria doesn't represent LavaPlayer library. It behaves like an audio player that's it.

**Comment by freyacodes** [comment]
There appears to be a lot of confusion regarding this issue. This was a problem with Lavaplayer that was promptly fixed in Lavalink before this issue was opened. It is not relevant to Victoria.

**Comment by Yucked** [comment]
Thanks for clearing it up Fred and MCOfficer.
Feel free to open an issue Chris if you come across any issues related to Victoria. 

Closing this issue now.
