### ISSUE TITLE
Skip function

### ISSUE THREAD

**Issue by Daniele122898** [Yucked/Victoria#5]
```csharp
public void Skip()
    {
      if (!this.IsConnected)
        throw new InvalidOperationException("Either this player isn't connected or connection isn't valid.");
      this.Dequeue(this.CurrentTrack);
      this._lavaSocket.SendPayload((LavaPayload) new StopPayload(this.Guild.Id));
      LavaTrack track = this.Queue.First?.Value;
      if (this.Queue.Count < 1 || track == null)
      {
        Volatile.Write(ref this.IsDisposed, true);
        throw new InvalidOperationException("Queue is empty. No more songs to play.");
      }
      this.CurrentTrack = track;
      Volatile.Write(ref this.IsDisposed, false);
      this._lavaSocket.SendPayload((LavaPayload) new PlayPayload(this.Guild.Id, track));
    }
```

I see some problems with this code. As far as i understand how the wrapper is constructed the first dequeue doesnt do anything. Since the current track isnt part of the queue. also if the queue is empty it will set this disposed variable again which bricks the leave. So it doesnt leave but brick the leave function.
also the track that is used for the next track isnt dequeued.

**Comment by Daniele122898** [comment]
And some things still seem to be wrong. As shown here
![](https://cdn.argonaut.pw/H3cXL2qa7dhTVSltlDI1DSreoTV1mfGT.png)
Even after calling dequeue after skipping myself.

**Comment by Daniele122898** [comment]
I can manually remove the song but the title etc of current track are the one from the old one... idk whats up

**Comment by Yucked** [comment]
Write you make a good point there. It wouldn't work for the very first track since the queue is empty.
*But* this shouldn't brick `LavaNode#LeaveAsync` since:

```cs
// LavaPlayer#Dispose
        private void Dispose()
        {
            _lavaSocket.SendPayload(new DestroyPayload(Guild.Id));
            VoiceChannel = null;
            TextChannel = null;
            CurrentTrack = null;
            Position = TimeSpan.MinValue;
            LastUpdate = DateTime.Now;
            Queue.Clear();
            Queue = null;
            Volatile.Write(ref IsDisposed, true);
        }
```

```cs
// LavaPlayer#DisconnectAsync
        internal async Task DisconnectAsync()
        {
            await VoiceChannel.DisconnectAsync();
            Dispose();
        }
```
Which is called by `LavaNode#LeaveAsync`:
```cs
        /// <summary>
        /// Disconnects <see cref="LavaPlayer"/> from a guild and returns a bool.
        /// </summary>
        /// <param name="guildId">Guild Id.</param>
        /// <returns><c>bool</c></returns>
        public async Task<bool> LeaveAsync(ulong guildId)
        {
            if (!_players.TryGetValue(guildId, out var player))
                return false;
            await player.DisconnectAsync();
            return _players.TryRemove(guildId, out _);
        }
```
It isn't checking for whether the playing is connecting or not. It disconnects from the VoiceChannel and sets everything in `LavaPlayer` to null.

For the image itself, I don't know what is going wrong where.

**Comment by Daniele122898** [comment]
In the image i implemented your skip function. I had 2 tracks in the queue. Calling skip by itself wouldnt remove anything from the queue and still show the old track as its player.currentTrack but play the new track. So i added some code that removes the newly playing track from the queue after skipping. Now whats weird is that the track that is playing after skip is indeed the new track, but when calling my now playing function which uses the player.currentTrack and its info it still displays the old track.

This is the skip function

```csharp
public async Task<Embed> SkipAsync(ulong guildId, ulong userId)
        {
            var player = _lavaNode.GetPlayer(guildId);
            if(player?.CurrentTrack == null) return Utility.ResultFeedback(
                Utility.BlueInfoEmbed,
                Utility.MusicalNote,
                "Not playing anything currently.").Build();
            
            

            using (var soraContext = new SoraContext())
            {
                var guildDb = Utility.GetOrCreateGuild(guildId, soraContext);
                if (!guildDb.NeedVotes)
                {
                    var track = player.CurrentTrack;
					// i use the skip here
                    player.Skip();
					//remove the track from the queue myself as it didnt when i tested.
                    if(player.CurrentTrack != null)
                        player.Dequeue(player.CurrentTrack);
                    return Utility.ResultFeedback(
                        Utility.BlueInfoEmbed,
                        Utility.MusicalNote,
                        $"Skipped: {track.Title}")
                        .WithUrl(track.Uri.ToString()).Build();
                }
            }

            [...] // unnecessary to show here
        }
```

The now playing command has some fancy additions that aren't needed but the important part is that i use player.currenttrack.title etc after the skip but it shows the wrong info as you can see in the image. It should display the guilty crown OST that was after it in the queue. 

```csharp
public Embed NowPlaying(ulong guildId)
        {
            var player = _lavaNode.GetPlayer(guildId);
            if(player?.CurrentTrack == null) return Utility.ResultFeedback(
                Utility.BlueInfoEmbed,
                Utility.MusicalNote,
                "Not playing anything currently.").Build();

            if (player.CurrentTrack.IsStream)
            {
                return Utility.ResultFeedback(
                    Utility.BlueInfoEmbed,
                    Utility.MusicalNote,
                    "Cannot display more info of a stream").Build();
            }

            double percentageDone = (100.0 / player.CurrentTrack.Length.TotalSeconds) *
                                    player.Position.TotalSeconds;

            int rounded = (int) Math.Floor(percentageDone / 10);
            string progress = "";
            for (int i = 0; i < 10; i++)
            {
                if (i == rounded) {
                    progress += " :red_circle: ";
                    continue;
                }
                progress += "▬";
            }

            return Utility.ResultFeedback(
                Utility.BlueInfoEmbed,
                Utility.MusicalNote,
                $"Currently playing by {player.CurrentTrack.Author}")
                .WithDescription($"**[{player.CurrentTrack.Title}]({player.CurrentTrack.Uri})**")
                .AddField(x =>
                {
                    x.IsInline = false;
                    x.Name = "Progress";
                    x.Value =
                        $"[{player.Position.ToString(@"mm\:ss")}] {progress} [{player.CurrentTrack.Length.ToString(@"mm\:ss")}]";
                })
                .Build();    
        }
```

**Comment by Yucked** [comment]
Yeah so for the past few hours I've been trying to write a skip function without much success.
```cs
        public void Skip()
        {
            if (!IsConnected)
                throw new InvalidOperationException("Either this player isn't connected or connection isn't valid.");
            var find = Queue.Find(CurrentTrack);
            LavaTrack track;
            if (find?.Value is null)
            {
                Stop();
                track = Queue.First?.Value;
            }
            else
            {
                Queue.RemoveFirst();
                track = Queue.First?.Value;
            }

            if (track is null)
                return;
            Play(track);
        }
```

**Comment by MonstahGames** [comment]
I didn't want to have to start a new issue so i'll just it here, It's not a big problem on my end, but when you call the Skip function on the last song it will replay that last song. Is this expected?

**Comment by Yucked** [comment]
@MonstahGames Yeah that's the issue that I'm having as well. I add x thing and it breaks y for some reason. Part of my wants to change the Queue to a HashSet but there is no guarantee of tracks being in correct order.

**Comment by Yucked** [comment]
So I was able to fix the skip thing with `ConcurrentQueue` but that makes Dequeue(LavaTrack/s) things useless coz ConcurrentQueue de-queues the first object from the queue.

If you guys are find with it, then I'll make sure and replace the default queue stuff.

Other option is to build a default collection based on LinkedList if you want to keep the same functionality. Something like:
```cs
public class LavaQueue<T> : LinkedList<T> {}
```
and somehow sync ConcurrentQueue with LinkedList, so on and so forth.

**Comment by Daniele122898** [comment]
i mean all u will ever need is to pop the first item from a queue. thats what a queue is for. no need to search a specific track. skipping a song is essential for any music player so having that working is way more important ^^.

**Comment by Yucked** [comment]
So, I've *fixed* the skip function by changing couple of things around and making queue stuff a lot easier to understand. I've tested it with 3 tracks and it seems to be working as expected. Further testing might be required or perhaps intense testing but it should get the basic work done.
