### ISSUE TITLE
[ BUG ] IsPlaying showing wrong value.

### ISSUE THREAD

**Issue by collectVood** [Yucked/Victoria#51]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

Sometimes randomly IsPlaying seems to be false even though the player is playing something. Triggered when trying to skip the current track.

### `Stacktrace / Screenshots`

Stacktrace: This operation is invalid since player isn't actually playing anything.

**Comment by Yucked** [comment]
What version are you on

**Comment by collectVood** [comment]
Was on the latest build (v4) switched to the nightly one but same issue

**Comment by Yucked** [comment]
Nightly isn't even stable but when skipping and playing a song it shouldn't throw that specific error.

I'll re-open this issue if you are still encountering this problem.
