### ISSUE TITLE
How to run LavaLink in the cloud?

### ISSUE THREAD

**Issue by Atm85** [Yucked/Victoria#53]
I have LavaLink running on a Linux instance using aws and I have port 2333 allowed though its firewall but I cant seem to connect to it
```csharp
await _lavaSocketClient.StartAsync(_client, new Configuration
    {
        Password = "password",
        Host = "public ip_v4", /*not gonna show the real host ip*/
        Port = 2333
});
```

**Comment by Yucked** [comment]
Uh can you ping lavalink or that port through another machine?
