### ISSUE TITLE
[ BUG ] V5 has a dependency on Socks v1.4.1 but it's not available on Nuget

### ISSUE THREAD

**Issue by DraxCodes** [Yucked/Victoria#54]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

As the title says, the latest version of Victoria requires Socks v1.4.1. However it's not currently available. As such we are unable to update to the latest version via Nuget. 

ℹ️ (Not an issue if we simply add the source ourselves, however I doubt everyone will do that, or even want to do that)

### `Stacktrace / Screenshots`

![SS](https://drax.codes/images/u/NIgCtf.png)

**Comment by Yucked** [comment]
Socks is now on nuget!
