### ISSUE TITLE
[ BUG ] VolumePayload gives a JSON that doesn't work

### ISSUE THREAD

**Issue by designed-re** [Yucked/Victoria#56]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

LavaPlayer.cs:188 | var payload = new VolumePayload(VoiceChannel.GuildId, volume);

new VolumePayload gives a JSON that doesn't work
### `Stacktrace / Screenshots`

Lavalink Error
2019-10-26 18:13:19.585  INFO 9920 --- [   XNIO-2 I/O-1] lavalink.server.io.SocketServer          : {"guildId":"542599372836438016","op":"volume"}
2019-10-26 18:13:19.696 ERROR 9920 --- [   XNIO-2 I/O-1] lavalink.server.io.SocketServer          : Exception while handling websocket message

org.json.JSONException: JSONObject["volume"] not found.

I Added code at line 199 with "File.WriteAllText("data.txt", Encoding.UTF8.GetString(JsonSerializer.SerializeToUtf8Bytes(payload, default)));"

Screenshot of VolumePayload
![image](https://user-images.githubusercontent.com/33867923/67617337-23ceb480-f81d-11e9-8b34-879644d14c2a.png)

**Comment by Yucked** [comment]
Hey which version is that?

**Comment by designed-re** [comment]
v5

**Comment by Yucked** [comment]
Thanks. I realized my mistake - well System.Text.Json mistake. Will push a change in few hours.

**Comment by designed-re** [comment]
:) thanks

**Comment by Yucked** [comment]
Fixed this issue in latest push. Waiting on nuget to remove the old version so I can upload the new one. Till then you can use myget: https://www.myget.org/F/yucked/api/v3/index.json

Closing this issue now. Feel free to reopen it.
