### ISSUE TITLE
[ PROPOSAL ]

### ISSUE THREAD

**Issue by A5ho9999** [Yucked/Victoria#59]
<p align="center">
<img src="https://media.giphy.com/media/2sYKSgbdkXvrpn7eBN/giphy.gif" width="40%"/>
</p>

---

### `Proposal Description:`

*Is it possible to add to the example, how to DisconnectAsync or DisposeAsync the LavaNode?.*

**Comment by Yucked** [comment]
That will vary from case to case basis. If you simply want to connect to a different `LavaNode` then you can have a command that simply calls: `LavaNode#DisconnectAsync()` then `LavaNode#DisposeAsync()`. Or, you can just call `DisposeAsync` as it will just call `DisconnectAsync` for you.
