### ISSUE TITLE
Change LavaNode.UpdateTextChannel parameters

### ISSUE THREAD

**Issue by D-Kay6** [Yucked/Victoria#61]
May I ask why you made the decision to have both the IGuild and ITextChannel as parameters for the method UpdateTextChannel in LavaNode?
As ITextChannel already has IGuild as a property, I fail to see why you would also want IGuild as a parameter for the method.

**Comment by Yucked** [comment]
Thanks for pointing that out! I came across that one couple days ago as well. Will remove the redundant parameter in next release.

**Comment by Yucked** [comment]
Fixed in commit https://github.com/Yucked/Victoria/commit/5f81e286cf87607ca1e5ff2634becf8cd59a7323.
