### ISSUE TITLE
[ PROPOSAL ] Know the user who queued the track

### ISSUE THREAD

**Issue by snoww** [Yucked/Victoria#62]
<p align="center">
<img src="https://media.giphy.com/media/2sYKSgbdkXvrpn7eBN/giphy.gif" width="40%"/>
</p>

---

### `Proposal Description:`

I would like to know who queued the track when getting the tracks. Not sure where the property should be added to, perhaps LavaTrack? not sure about that one

### `Pseudo Code:`

maybe something like 
`track.QueuedBy`

**Comment by Yucked** [comment]
Hey, you can extend `LavaTrack` or have a class that implements `IQueueable`. For example:

```cs
public sealed class Request : IQueueable {
     public LavaTrack Track { get; set; }
     public ulong UserId { get; set; }
     public IGuildUser User { get; set; }
}
```

```cs
...
if !(lavaPlayer.Queue.TryDequeue(out var queueable))
     return;

var request = queueable as Request;
await lavaPlayer.PlayAsync(request.LavaTrack);
await ReplyAsync($"Now Playing: {request.LavaTrack.Title}\nRequested By: {request.User}");
```

**Comment by snoww** [comment]
I implemented `IQueueable`, but when I queue the track, I lose the user I lose the user information. Same issue when getting the player’s current track. I’m not sure how I’d go on extending LavaTrack

**Comment by Yucked** [comment]
Can you show me your code? I can help debug that issue and extending LavaTrack is simple.

```cs
public sealed class CustomTrack : LavaTrack {

}
```
Then instead of queueing LavaTrack you queue your CustomTrack. And cast IQueueable to CustomTrack when de-queueing from queue.

**Comment by snoww** [comment]
For the interface method heres my implementation:

```
public class RokiRequest : IQueueable
{
    public LavaTrack Track { get; set; }
    public IGuildUser User { get; set; }
}
```

and then I create a new request and add it to the queue.
```
var request = new RokiRequest {Track = result.Tracks.FirstOrDefault(), User = ctx.User as IGuildUser};
player.Queue.Enqueue(request);
```

this all works fine. But when I cannot get the custom request when doing getting the current track info
i.e.
```
var currTrack = player.Track;
```
the `currTrack` would be a `LavaTrack`

**Comment by Yucked** [comment]
Yeah then my previous reply should be of help.

**Comment by snoww** [comment]
So when I extend LavaTrack, would it be something like this?
```cs
public class RokiTrack : LavaTrack
{
    public IGuildUser User { get; set; }
}
```
and then I do
```cs
var request = (RokiTrack) result.Tracks.First();
request.User = ctx.User as IGuildUser;
player.Queue.Enqueue(request);
```
correct?

**Comment by Yucked** [comment]
Yes, that should be it.

**Comment by snoww** [comment]
I get this error when casting 
```
System.InvalidCastException: Unable to cast object of type 'Victoria.LavaTrack' to type 'Roki.Modules.Music.Common.RokiTrack'.
```

**Comment by Yucked** [comment]
Rip I know why. Okay so when you get tracks from search they are not RokiTrack. What you need to do is.
```cs
var track = Tracks.FirstOrDefault();
var RokiTrack = track as RokiTrack;

```
Try that and Lmk.

**Comment by snoww** [comment]
heres what I did
```cs
var track = result.Tracks.FirstOrDefault();
var request = track as RokiTrack;
if (request == null)
{
    _log.Error("Error casting");
    return;
}
```
the if statement is true every time

do I need to add the `LavaTrack` properties in `RokiTrack`? I dont think so right? since its extended from it.

Edit: what I've found out is that I would need to have a constructor in RokiTrack that sets the properties from LavaTrack, but I cannot since the set is private in LavaTrack

**Comment by Yucked** [comment]
Okay that was dumb on my part. Casting hierarchy doesn't work that way. So, yeah I will have to creator a CTOR for LavaTrack. I'll do it in next release hopefully in few hours.

**Comment by Yucked** [comment]
This feature has been added in v5.1.9. You are now able to extend LavaTracks.
