### ISSUE TITLE
[ BUG ] "Connected and new voice channel ids are the same"

### ISSUE THREAD

**Issue by collectVood** [Yucked/Victoria#63]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

Version: 5.1.2

### `Describe the bug/issue.`

So this issue occurs pretty much randomly when the bot looses connection and seems like it's not really reproducable for me.

This is the main code I use when playing music to check if the player exist, if not the bot should join the channel:
`            var player = _lavaNode.HasPlayer(Context.Guild)
                ? _lavaNode.GetPlayer(Context.Guild)
                : await _lavaNode.JoinAsync((Context.User as IGuildUser).VoiceChannel, Context.Channel as ITextChannel);`

Seems like the issue is caused in the JoinAsync in which the old player voicechannel is the same as the new one. Just to confirm again the bot is not connected to any voice channel when this happens. It was connected to this voicechannel before though before it "randomly" lost connection.

### `Stacktrace / Screenshots`

`Connected and new voice channel ids are the same.`

**Comment by collectVood** [comment]
Could this be in relation to me connecting bots on ready? Possibly it not updating correctly if connection is directly lost on ready?

**Comment by Yucked** [comment]
So, I may have a fix for this but I can't really test it out since I don't know how to make it behave like it lost connection. 

If you're willing to fork Victoria and test it out lemme know.

**Comment by collectVood** [comment]
Sure thing, I will do thanks for helping 👍

**Comment by Yucked** [comment]
I remember you hooked into `UserVoiceStateUpdated` event. Does that even fire when you lose connection or when you reconnect?

**Comment by Yucked** [comment]
```cs
        private Task OnUserVoiceStateUpdatedAsync(SocketUser user, SocketVoiceState oldState,
                                                  SocketVoiceState newState) {
            if (_socketClient?.CurrentUser == null || user.Id != _socketClient.CurrentUser.Id)
                return Task.CompletedTask;

            SocketVoiceChannel GetChannel() {
                var channel = oldState.VoiceChannel ?? newState.VoiceChannel;
                var userChannel = channel.Guild.CurrentUser.VoiceChannel;

                if (newState.VoiceChannel == null && oldState.VoiceChannel != null) {
                    return oldState.VoiceChannel;
                }

                return newState.VoiceChannel ?? channel;
            }

            var guildId = GetChannel()?.Guild.Id;
            if (!_playerCache.TryGetValue(guildId.GetValueOrDefault(), out var player))
                return Task.CompletedTask;

            if (oldState.VoiceChannel == null && newState.VoiceChannel != null) {
                // Check if bot is connected?
            }
            else if (oldState.VoiceChannel != null && newState.VoiceChannel == null) {
                // Check if bot is disconnected?
            }
            else if (oldState.VoiceChannel != null && newState.VoiceChannel != null) {
                // Check if lost connection?
            }
            else if (oldState.VoiceChannel != null && newState.VoiceChannel != null
                                                   && oldState.VoiceChannel.Id != newState.VoiceChannel.Id) {
                // Check if channels moved?
            }
            else {
                player.VoiceState = newState;
                player.VoiceChannel = newState.VoiceChannel;
            }

            return Task.CompletedTask;
        }
```

Can you replace the comments with your logging or Victoria's logging?

**Comment by collectVood** [comment]
Seems to not trigger for me when I cut the connection completly, what does trigger though is the LavaNode.OnWebSocketClosed event. Also when moving the bot it also counts as ` Check if lost connection?` because in that case old and new voicechannel would be not null, therefore the last if channels moved wouldn't trigger if set up in this order

**Comment by Yucked** [comment]
Well if connection isn't lost then it should have the channels as not null since nothing was sent via discord to let it know that the new state Channel is null. But since you say it doesn't trigger anything I think that makes a very big problem no both sides.

**Comment by Yucked** [comment]
@collectVood Do you still encounter this issue?
