### ISSUE TITLE
[ BUG ] MoveChannelAsync() causes newState.VoiceChannel in OnUserVoiceStateUpdated to be null

### ISSUE THREAD

**Issue by collectVood** [Yucked/Victoria#65]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---
Version: 5.1.2

### `Describe the bug/issue.`

For some reason it seems like whenever I use MoveChannelAsync() (on a voicechannel) it causes newState.VoiceChannel in OnUserVoiceStateUpdated to be null even though the bot is connected to a voicechannel.

### `Stacktrace / Screenshots`

*When debugging yourself, you can attach screenshots of Autos/Locals tabs in Visual Studio.*

**Comment by collectVood** [comment]
Same goes when I manually check if the user is connected to a voicechannel in OnUserVoiceStateUpdated

**Comment by collectVood** [comment]
Delaying the check `if ((user as IGuildUser)?.VoiceChannel == null)` seems to not solve my issue

**Comment by Yucked** [comment]
That doesn't seem like a Victoria issue but rather a Discord.NET issue. Yes, the `newState.VoiceChannel` will be null since you will first have to disconnect then join a new channel.

**Comment by collectVood** [comment]
Oh true, that makes sense... Thank you :)
