### ISSUE TITLE
[ BUG ] Search Request Actively Refused

### ISSUE THREAD

**Issue by Naendo** [Yucked/Victoria#66]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

Hey,
so i was trying to implement a music bot with .net core 3.0 and this guy:
![image](https://user-images.githubusercontent.com/56106169/78672297-c026d800-78e0-11ea-945e-253cb7b045aa.png)

caused an major issue: 
![image](https://user-images.githubusercontent.com/56106169/78672327-c9b04000-78e0-11ea-8cee-c74e284fe767.png)

I downloaded your given Example "Party-Bot" and the same error occured.

After some research i found this article: https://support.discordapp.com/hc/de/articles/360035010351--Known-Issue-Music-Bots-Not-Playing-Music-From-Certain-Sources

Is it possible that SearchRequest cannot be executed with the current Version of Victoria/LavaLink?

Thanks for your responses!

### `Stacktrace / Screenshots`
![image](https://user-images.githubusercontent.com/56106169/78672570-1eec5180-78e1-11ea-88e5-e530ebef5143.png)

**Comment by Yucked** [comment]
Uh, did you solve it already?

**Comment by Naendo** [comment]
Yep sorry 🌵
