### ISSUE TITLE
[ HELP ] OnTrackFinished is no longer working for me

### ISSUE THREAD

**Issue by ChrisVDB36** [Yucked/Victoria#67]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

Hi,

I am re-doing my bot, and, when I try out the music tools im running in a problem with a specific event. The "OnTrackFinished" event.
Somehow the event "OnTrackFinished" for the LavaSocketClient seems to be no longer working for me.. To make sure, I commented out all code in my method and just put a Console.WriteLine() to see some testing text in console whenever a track is finished but nothing is showing up.
Even when I manually stop the track using my command !stop, the track stops playing but the event does not fire either.
But on the other hand the "Log" event still works... and they both get assigned at the same time like this:

_lavaSocketClient.Log += OnLavaSocketClientLog;
_lavaSocketClient.OnTrackFinished += OnTrackFinishedAsync;

The first one works (Log), but OnTrackFinished doesnt, I am using DI for all this (with AddSingleton) and I set these event methods when the "Ready" event fires from my DiscordSocketClient
Everything else works fine, music runs etc.. but he wont fire the finished event and I am clueless why this is happening.
I tried it on my older bot and the issue seems to be the same, log event works but finished event doesnt.
I also just tried the "StreamMusicBot" from Drax, even in there the event is not been fired.

To test this further I also tried to queue up some songs in all 3 bots, none of them fired the event when the track was done. Am I doing something wrong here, I really need help with this please.
This is the code I use to do the event work:

private async Task OnTrackFinishedAsync(LavaPlayer player, LavaTrack track, TrackEndReason reason)
        {
            if (!reason.ShouldPlayNext())
                return;

            if (!player.Queue.TryDequeue(out var item) || !(item is LavaTrack nextTrack))
            {
                await player.TextChannel.SendMessageAsync("There are no more tracks in the queue.");
                return;
            }

            await player.PlayAsync(nextTrack);
        }

All help is really appriciated, have a nice day.
Greetings

EDIT:
He also seems to be stuck in the "IsPlaying" because whenever a track is done playing, no more sound is been emited but when you try to add a new song, he will queue the song because he thinks he is still playing but he isnt anymore, this is so weird and I dont understand whats happening, sorry if my english is a bit off

**Comment by Yucked** [comment]
Hey can you tell me which versions of Victoria is that happening on?
And, what's the lavalink version you are using?
Also, your Java version.

**Comment by ChrisVDB36** [comment]
Hi,

I am using Victoria version 4.0.17
Lavalink version is v3.3.1, updated that a day ago from https://github.com/Frederikam/Lavalink/releases
Java version is 12.0.2 (2019-07-16)

I have 2 bots using the same versions from above, one is running on .NET Core & the other on just .NET and the problem seems to be in both of the bots

**Comment by Yucked** [comment]
Okay for some odd reason they have added anything to `IMPLEMENTATION.md` and nothing in `CHANGELOG.md` regarding TrackFinished event.

I'll check out v4 and v5 to see if they work with latest release

**Comment by Yucked** [comment]
Okay wanted to give a quick update. The error was caused by a missing event it seems. Let me know if you come across any issues.

**Comment by renanrcp** [comment]
> Okay wanted to give a quick update. The error was caused by a missing event it seems. Let me know if you come across any issues.

I'll test it later

**Comment by ChrisVDB36** [comment]
> Okay wanted to give a quick update. The error was caused by a missing event it seems. Let me know if you come across any issues.

Hey, 
I updated to 4.0.18 and it works again 👯 
Thanks a lot for taking your time to look into this, my bot is back working properly again 👍
