### ISSUE TITLE
[ BUG ] RemoveRange doesn't work properly

### ISSUE THREAD

**Issue by Daniele122898** [Yucked/Victoria#68]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

Calling `player.Queue.RemoveRange(0,9)` only removes the first 2 entries. To properly do a multi skip i had to use
```csharp
for (int i = 0; i < queueRemove; i++)
{
    player.Queue.TryDequeue(out _);
}
```

**Comment by Yucked** [comment]
Can you tell me what version you are using?

**Comment by Daniele122898** [comment]
v5.1.3

**Comment by Daniele122898** [comment]
Actually i think it even only removed 1 entry. Since i also call skip after it that's why 2 where skipped. 
So that function seems to only get rid of the first track in the queue

**Comment by Yucked** [comment]
Okay so I've fixed this one. The initial version of that method is this:

```cs
public ICollection<T> Remove(int index, int count) {
			if (index < 0) {
				throw new ArgumentOutOfRangeException(nameof(index));
			}

			if (count < 0) {
				throw new ArgumentOutOfRangeException(nameof(count));
			}

			if (Count - index < count) {
				throw new ArgumentException("Math");
			}

			var tempIndex = 1;
			var removed = new T[count];
			lock (_list) {
				var currentNode = _list.First;
				while (tempIndex != index && currentNode != null) {
					tempIndex++;
					currentNode = currentNode.Next;
				}

				var nextNode = currentNode?.Next;
				for (var i = 0; i < count && currentNode != null; i++) {
					var tempValue = currentNode.Value;
					removed[i] = tempValue;

					_list.Remove(currentNode);
					currentNode = nextNode;
					nextNode = nextNode?.Next;
				}

				return removed;
			}
		}
```

I might have to optimize it a bit more or if others can help out in my Guild but if not then this would be it.

**Comment by Daniele122898** [comment]
Can you push this so i can alter it?

**Comment by Yucked** [comment]
Sure thing! Also if you want to test out the changes: https://www.myget.org/F/yucked/api/v3/index.json

**Comment by Yucked** [comment]
I'll be closing this issue. Feel free to reopen it if it doesn't work out.
