### ISSUE TITLE
[ BUG ] Stats event doesn't fire

### ISSUE THREAD

**Issue by Daniele122898** [Yucked/Victoria#69]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

```
[18:41:56 DBG] {"playingPlayers":0,"op":"stats","memory":{"reservable":8573157376,"used":32857352,"free":271229688,"allocated":304087040},"players":0,"cpu":{"cores":16,"systemLoad":0,"lavalinkLoad":0.0684084030621328},"uptime":11861}
```

The stats event is definitely sent by lavalink but the onstatsevent is never fired by victoria. So smth is breaking there. 

```csharp
 private Task OnStatsReceived(StatsEventArgs e)
        {
            _log.LogTrace("Received Stats from LavaLink");
            _audioStatsService.SetStats(e);
            return Task.CompletedTask;
        }
```
This event is never triggered.

**Comment by Yucked** [comment]
Can you tell me what version you are using?

**Comment by Daniele122898** [comment]
v5.1.3

**Comment by Yucked** [comment]
Hey I just tested it myself and I'm receiving updates. 
![image](https://user-images.githubusercontent.com/20461656/81505941-cb866e00-92a7-11ea-812b-abedbddc3b79.png)

Lavalink also seems to be working fine:
![image](https://user-images.githubusercontent.com/20461656/81505958-f375d180-92a7-11ea-8996-58c38147d233.png)

Code: https://github.com/Yucked/Avis/blob/master/src/Services/MusicService.cs

**Comment by Daniele122898** [comment]
Im receiving all events but not the OnStatsReceived. 
i have it hooked `_node.OnStatsReceived += OnStatsReceived;` and everything but nothing is coming in. All other events are fine but i never receive stats

https://github.com/Daniele122898/SoraBot-v2/blob/dev/SoraBot/SoraBot.Bot/Modules/AudioModule/AudioEventHandler.cs#L33-L41

Also if you enable debug logging you can see that victoria receives it but the proper c# event is never triggered

**Comment by Yucked** [comment]
That's very strange. If you have VS could you perhaps run your bot in Debug mode and check the output window for any exceptions related to Victoria?

![image](https://user-images.githubusercontent.com/20461656/81506837-055a7300-92ae-11ea-9171-f51ba05ee3ac.png)

That might narrow the problem down a bit. If nothing is thrown then it's probably not Victoria which would then lead me to ask you about your Lavalink version and Java version.

**Comment by Daniele122898** [comment]
I did that. that's where i have this from: `[18:41:56 DBG] {"playingPlayers":0,"op":"stats","memory":{"reservable":8573157376,"used":32857352,"free":271229688,"allocated":304087040},"players":0,"cpu":{"cores":16,"systemLoad":0,"lavalinkLoad":0.0684084030621328},"uptime":11861}`

This is output from victoria so it definitely receives the stats payload. 
I use the latest lavalink 3.3.1 and java 13 as recommended. 

It cant be Lavalink since the payload obviously gets to victoria. But there seem to be no exceptions.

I have the victoria log hooked into my serilog which outputs everything and would email me on exceptions via sentry. Nothing throws but no events ever reach the event handler. its weird

**Comment by Yucked** [comment]
Did you have this problem before? Last known version where it was working?

**Comment by Daniele122898** [comment]
I haven't used Victoria for a while but i think in version 4.0.17 it still worked. If i remember correctly.

**Comment by Yucked** [comment]
I'm still looking into it but so far I can't seem to figure out the problem. I know in v4 I used Newtonsoft.Json and in v5 I'm using STJ and custom converters but custom converters do throw hard exceptions if something doesn't work out. In which case Victoria isn't throwing any errors on your end at all regarding events.

Since reset of your events are working fine, could you perhaps fork Victoria, add a Console.WriteLine() kind of debug stuff in LavaNode#OnReceiveAsync  https://github.com/Yucked/Victoria/blob/v5/src/LavaNode.cs#L481

And in key areas https://github.com/Yucked/Victoria/blob/v5/src/Converters/WebsocketResponseConverter.cs#L100

This is the only way I can think of debugging this. If not I can push a preview version tomorrow with the debug line changes and you can add it and let me know.

**Comment by Daniele122898** [comment]
hey sorry im currently studying for finals. not sure yet when i get to it but i'll try it out as soon as i got time again

**Comment by Yucked** [comment]
Hey, no worries! I'm also busy studying for finals. Good luck!! I have also pushed out v5.1.6 on nuget with few changes that *might* have fix the problem you're having.

**Comment by Yucked** [comment]
@Daniele122898  Were you able to resolve it in newer versions of Victoria? I'll be closing this issue tomorrow.

**Comment by Daniele122898** [comment]
hey im sorry i didnt touch the coding project in a while since my exams are starting now so im deep into the studies. but you can close this if you want and in a month or two when im back i'll check :)

**Comment by Yucked** [comment]
Alrighty. Good luck with your exams!

**Comment by Daniele122898** [comment]
Just wanted to let you know that whatever you did seems to have fixed the issue with the missing stats :D
