### ISSUE TITLE
[ BUG ] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by Amoo0001** [Yucked/Victoria#70]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

Probably the same issue as this user, but I can't figure it out:
https://github.com/Yucked/Victoria/issues/66

When trying to search YouTube, an exception is thrown.  Do I need to log in somehow?  Is there a standalone executable I need to be running alongside my bot?  I'm new to Victoria and LavaLink.

### `Stacktrace / Screenshots`

```
07:04:50 [Error] Command: Discord.Commands.CommandException: Error occurred executing "play" for Amoo#0001 in Demon Girls/??|bots.
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Victoria.LavaNode`1.SearchAsync(String query)
   at DemonGirls.Modules.MusicModule.Play(String query) in C:\Users\Amy\source\repos\DemonGirls\DemonGirls\Modules\MusicModule.cs:line 75
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   --- End of inner exception stack trace ---
07:04:50 [Verbose] Command: Executed "play" for Amoo#0001 in Demon Girls/??|bots
```

**Comment by Yucked** [comment]
Did you follow the Readme and wiki?

**Comment by Amoo0001** [comment]
Yes, very carefully.  I found an application called Lavalink, is this the same Lavalink?  Do I need to run this application also?
https://github.com/Frederikam/Lavalink

**Comment by Amoo0001** [comment]
Oh!  I missed a part of the Wiki!  I might not need help anymore, I'm so sorry.  Let me see if I can get it to work, and I'll close this if so.

**Comment by Amoo0001** [comment]
Ok search isn't crashing anymore now that I'm running Lavalink, but it's not returning any results for any query.  Do I need to customize application.yml somehow?  I know YAML but I'm not sure what needs to be changed.

**Comment by Amoo0001** [comment]
I got it to work, thanks for pointing me back to the Wiki... I was very careful but I was operating on little sleep and I missed a paragraph that was rather important!  Thanks again and sorry for the noise.

Take care <3
- Amy

**Comment by Yucked** [comment]
No worries! I'm glad you figured it out. 👍☺️

**Comment by djthegr8** [comment]
having the same problem.....
It keeps saying Waiting x seconds before attempt #x

**Comment by Yucked** [comment]
@djthegr8 This problem usually happens if:

1. You downloaded and ran Lavalink.jar without download application.yml
2. The application.yml is not in the same directory as lavalink.jar
3. You specified a different port and host in application.yml and didn't change it in `LavaConfig`
4. You started Lavalink.jar programmatically e.g Process.Start("java -jar Lavalink.jar") and didn't specify WorkingDirectory for ProcessStartInfo

**Comment by djthegr8** [comment]
I used the PartyBot test, and i do have application.yml.**example** in the same folder (is that wrong?)

**Comment by djthegr8** [comment]
application.yml != application.yml.example or something?

**Comment by Yucked** [comment]
You should rename it to `application.yml` instead of `application.yml.example`.

**Comment by djthegr8** [comment]
Explains..lemme test it
Thx a ton (nice lib btw)

**Comment by Yucked** [comment]
Let me know how it goes. And, thank you! Glad you like it.

**Comment by djthegr8** [comment]
Yay it worked! Thx

**Comment by djthegr8** [comment]
Btw does it only work on links?

**Comment by Yucked** [comment]
No, you can also use raw queries such as "The Weeknd Valerie", etc.

Although, there are 3 methods. `SearchAsync` searches links only. `SearchYouTubeAsync` & `SearchSoundCloudAsync` handle raw queries.

You can sum them into one line though:
```cs
var searchResult = await (Uri.IsWellFormedUriString(query, UriKind.Absolute) ? SearchAsync(query) : SearchYouTubeAsync(query));
```

**Comment by valen030** [comment]
> No, you can also use raw queries such as "The Weeknd Valerie", etc.
> 
> Although, there are 3 methods. `SearchAsync` searches links only. `SearchYouTubeAsync` & `SearchSoundCloudAsync` handle raw queries.
> 
> You can sum them into one line though:
> 
> ```cs
> var searchResult = await (Uri.IsWellFormedUriString(query, UriKind.Absolute) ? SearchAsync(query) : SearchYouTubeAsync(query));
> ```

Hi, my bot was able to join and leave according to command but i have a problem with this line
`var search = Uri.IsWellFormedUriString(query, UriKind.Absolute) ? await _lavaNode.SearchAsync(query) : await _lavaNode.SearchYouTubeAsync(query);`

which is executed when "play" command.
The error i get is "No connection could be made because the target machine actively refused it."
