### ISSUE TITLE
[ PROPOSAL ] Media from files/urls

### ISSUE THREAD

**Issue by hiilikewiki** [Yucked/Victoria#71]
<p align="center">
<img src="https://media.giphy.com/media/2sYKSgbdkXvrpn7eBN/giphy.gif" width="40%"/>
</p>

---

### `Proposal Description:`

Does what it says on the tin, so I don't have to use reflection.

**Comment by Yucked** [comment]
I'm sorry I don't understand what you're asking for here. What are you using reflection for? Where are you using it? What does it have to do with media from file/url/Victoria?

**Comment by hiilikewiki** [comment]
Unless I misunderstood something, how should I go about playing files from a link?

**Comment by Yucked** [comment]
Playing files from a link? Do you've a folder online that host these files? If so, get individual direct links of these files and use `LavaNode#SearchAsync(MY_FILE_DIRECT_LINK)`. Anything that is a directory or a direct link, `SearchAsync` should be used for it. Also, make sure in your `application.yml` you enable `local` if these files are local and `http` if the files are direct.

**Comment by hiilikewiki** [comment]
Oh, right that's cool. I was invoking WithUrl xD Thanks
