### ISSUE TITLE
[ BUG ] FriendlyException: Something broke while playing the track (YouTube Search)

### ISSUE THREAD

**Issue by djthegr8** [Yucked/Victoria#72]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

#### `Original:`
I was playing from yt and got this error, there is no sound being played.
FriendlyException: Something broke while playing the track

#### `Revised:`
When making a YouTube search either via a raw query (``!Search The Weeknd Valerie``) or passing a direct link (``https://youtube.com/watch?v=ABCD1234``) search doesn't return anything and Lavalink throws an exception (Screenshot attached below).

This problem is not related to Victoria. If Lavalink isn't able to parse out audio links or if something changed on YouTube's end, Lavalink won't be able to return any results.

### `Stacktrace / Screenshots`

![image](https://user-images.githubusercontent.com/44142719/86429583-a34a4700-bd0d-11ea-8d60-0abebbf743ec.png)

### `Update:`
It seems many of you can't find songs on YouTube when using Lavalink. Please know that this is not related to Victoria.

What you need to be on the lookout for:
Lavalink issues: <https://github.com/Frederikam/Lavalink/issues>
Lavalink CI releases: <https://ci.fredboat.com/viewLog.html?buildId=lastSuccessful&buildTypeId=Lavalink_Build&tab=artifacts&guest=1>

Please make sure you download and install Lavalink from their CI ^.
Till then please use `SoundCloudSearchAsync` to search tracks or have a null check before adding your track to queue:

1. Check if SearchResponse returns null.
2. Check if searchResponse.LoadStatus returns null or failed or no search.
3. Check if track collection is empty.
4. Check if selected track is null (FirstOrDefault)
5. If all of that returns null, search again and requeue

**Comment by Yucked** [comment]
That's lavalink not being able to play the track. You can requeue it and hope that it plays.

**Comment by djthegr8** [comment]
The same thing happens with every yt video, altho soundcloud works

**Comment by djthegr8** [comment]
well nothing works.......
although i guess the problem is not in victoria, so should i close?

**Comment by Yucked** [comment]
No. You can try getting the latest lavalink release from their CI and see if that fixes it.

**Comment by djthegr8** [comment]
I am using the very latest build, downloaded it day before yesterday.

**Comment by Yucked** [comment]
Then I'm sorry. There is nothing that can be done on Victoria's end. If Lavalink puts out a fix, you'll have to try that. 

Update: Fixed in latest version of Lavalink.
