### ISSUE TITLE
[ BUG ] https lavalink server

### ISSUE THREAD

**Issue by Eloncase** [Yucked/Victoria#74]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

Hi! My Lavalink server is running behind nginx proxy and is configured to use SSL. Currently it's not possible to connect Victoria to secured Lavalink server mostly because of hardcoded [http](https://github.com/Yucked/Victoria/blob/582a94c4de433d1a912ce7a11e20dc2db01a0306/src/LavaNode.cs#L135) and [ws](https://github.com/Yucked/Victoria/blob/582a94c4de433d1a912ce7a11e20dc2db01a0306/src/LavaSocket.cs#L82) protocols at those lines.

It would've been nice to have a `bool` variable in configuration in order to use secured protocols.

On top of that (but that's more like a feature request) it would've been great to have a way to configure `User-Agent` header. It does help a lot when viewing server logs.

I've actually implemented both of those things so if you are okay with those changes I can submit a PR.

### `Stacktrace / Screenshots`

Server response when trying to connect to https Lavalink server.
```
400 Bad Request
The plain HTTP request was sent to HTTPS port
```

Client side.
```
17:34:42 [Error   ] Exception           : System.Net.WebSockets.Client: The server returned status code '400' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
```

**Comment by Yucked** [comment]
Does it work with the changes you implemented? If so, do open a PR, edit the project file and update the release notes to reflect the changes you made and bump up the patch version. I'll review those changes next morning before merging/approving them.
