### ISSUE TITLE
[ Question ] Why is the default Player volume set to 0?

### ISSUE THREAD

**Issue by dakata1337** [Yucked/Victoria#80]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

This is more like a question and not a bug. Why is the default Player volume set to 0? If I set it to 100 it sounds the same.

Code:
```
var player = _lavaNode.GetPlayer(context.Guild);
Console.WriteLine(player.Volume);
```

**Comment by Yucked** [comment]
It's not initialized in the CTOR of LavaPlayer, the actual default volume is 100 on Lavalink's side. On Victoria's end the volume is whatever value you set it to in UpdateVolumeAsync

**Comment by dakata1337** [comment]
> It's not initialized in the CTOR of LavaPlayer, the actual default volume is 100 on Lavalink's side. On Victoria's end the volume is whatever value you set it to in UpdateVolumeAsync
