### ISSUE TITLE
[ BUG ] Stop streaming audio

### ISSUE THREAD

**Issue by hellox5** [Yucked/Victoria#85]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

is there a reason to stop streaming audio? although there is no problem appearing in the console, to fixing this problem must disconnect from Lavalink and reconnect, I think the token of the voice channel is changing and Victoria doesn't send it to WebSocket, This problem has appeared a lot and I have the latest version of Victoria and Lavalink.

**Comment by cxnky** [comment]
I'm also getting an issue similar to this: all youtube livestreams seem to automatically stop at the 6 hour mark?

**Comment by Yucked** [comment]
The information given doesn't narrow it down. Victoria does send the voice channel token every time voice server update is received. 

```cs
		private async Task OnVoiceServerUpdatedAsync(SocketVoiceServer voiceServer) {
			if (!_playerCache.TryGetValue(voiceServer.Guild.Id, out var player)) {
				return;
			}

			player.VoiceServer = voiceServer;
			var payload = new ServerUpdatePayload {
				SessionId = player.VoiceState.VoiceSessionId,
				GuildId = $"{voiceServer.Guild.Id}",
				VoiceServerPayload = new VoiceServerPayload {
					Token = voiceServer.Token,
					Endpoint = voiceServer.Endpoint
				}
			};

			await _lavaSocket.SendAsync(payload)
			   .ConfigureAwait(false);
		}
```
