### ISSUE TITLE
[ BUG ] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by Emptyn3ss** [Yucked/Victoria#88]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`
Hello.

I got an issue with my Discord bot. When I try to use the SearchAsync () or SearchYouTubeAsync () method, I get this error message. I disabled the firewall but it didn't work like the other solutions I've used.

I will be very grateful for your help in solving this problem.

### `Stacktrace / Screenshots`
![image](https://user-images.githubusercontent.com/85898043/121937439-5c553600-cd53-11eb-98eb-2f8ec4031237.png)

**Comment by Yucked** [comment]
Is Lavalink running on that port? Are you able to connect to Lavalink via websocket?

**Comment by Emptyn3ss** [comment]
Subscribed OnLog event returned this message:

![image](https://user-images.githubusercontent.com/85898043/121939326-958ea580-cd55-11eb-859d-340ea504fc82.png)

**Comment by Yucked** [comment]
Which means you aren't connected to Lavalink. 
https://yucked.github.io/Victoria/guides/getting-started/setup.html?tabs=tabid-lavagit%2Ctabid-ngt

**Comment by Emptyn3ss** [comment]
I'm really appreciate you for help. Thank you!
