### ISSUE TITLE
[ BUG ] can't skip the track when got stuck

### ISSUE THREAD

**Issue by unwell35** [Yucked/Victoria#90]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

There is not much to explain, but when the track got stuck I can't skip it, always gets this error: Player state doesn't match any of the following states: Connected, Playing, Paused.

### `Stacktrace / Screenshots`
![issue](https://user-images.githubusercontent.com/37715638/127085039-85a24d12-c57a-49eb-b806-23b42f51b7ab.png)

**Comment by Yucked** [comment]
Resolved in commit b75e22269f62750a1487c6fc400569e9d645e635. It only checks for `PlayerState#None`.
