### ISSUE TITLE
[ PROPOSAL ] Add support for Discord.Net Labs

### ISSUE THREAD

**Issue by quinchs** [Yucked/Victoria#91]
<p align="center">
<img src="https://media.giphy.com/media/2sYKSgbdkXvrpn7eBN/giphy.gif" width="40%"/>
</p>

---

### `Proposal Description:`
Create a build targeting [Discord.Net Labs](https://github.com/Discord-Net-Labs/Discord.Net-Labs) so users who are using labs can also use victoria

**Comment by Yucked** [comment]
It is a complete rewrite of D.NET? Any D.NET dependencies? If you have Discord.Net.WebSocket as a dependency then Victoria should work fine with D.NET Labs.

**Comment by quinchs** [comment]
Labs is a rework of dnet, the two arnt compatable

**Comment by quinchs** [comment]
people using labs cant use victoria as victoria requires a dnet component

my suggestion is to have another build of victoria that targets the labs websocket component

**Comment by Yucked** [comment]
Sure I could do that but I won't be placing it on Nuget. People will have to reference MyGet in their projects and DNet Labs should have been a fork of D.NET to avoid having a rebranded d.net clone.

I'll have to package up later on MyGet, if your users ask for Victoria support please ask them to add the following in their project file:

```xml
	<PropertyGroup>
		<RestoreAdditionalProjectSources>https://www.myget.org/F/yucked/api/v3/index.json</RestoreAdditionalProjectSources>
	</PropertyGroup>
```

**Comment by d4n3436** [comment]
Temporary workaround: Downgrade Victoria to version 5.1.11. This version works fine with Labs.

**Comment by Aaalexer** [comment]
It doesnt work on Victoria 5.1.11

**Comment by Aaalexer** [comment]
When discord.labs support will arrive?

**Comment by quinchs** [comment]
> When discord.labs support will arrive?

>I'll have to package up later on MyGet, if your users ask for Victoria support please ask them to add the following in their project file:
```xml
<PropertyGroup>
	<RestoreAdditionalProjectSources>https://www.myget.org/F/yucked/api/v3/index.json</RestoreAdditionalProjectSources>
</PropertyGroup>
```

**Comment by Aaalexer** [comment]
It doesnt work

**Comment by Yucked** [comment]
My bad fellas, if 5.1.11 works with dnetlabs according to @d4n3436 then 5.2 should work too as only few things were changed:

v5.1.11:
```xml
	<ItemGroup>
		<PackageReference Include="Discord.Net.WebSocket" Version="2.2.0"/>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.3"/>
	</ItemGroup>
```


v5.2:
```xml
	<ItemGroup>
		<PackageReference Include="Discord.Net.WebSocket" Version="2.4.0"/>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.2"/>
		<PackageReference Include="System.Text.Json" Version="5.0.2"/>
	</ItemGroup>
```

And targetframework updated from 3.0 to 3.1.

**Comment by Aaalexer** [comment]
I dont know, it still doesnt work

**Comment by AlexandreBazeaud** [comment]
I'm using 6.0 with d.net labs and it works fine for me, no problem

**Comment by Aaalexer** [comment]
NET 6?

**Comment by AlexandreBazeaud** [comment]
Victoria 6.0 and Net 5.0

**Comment by Aaalexer** [comment]
Im asking about victoria 5.2+ and net5

**Comment by AlexandreBazeaud** [comment]
Then saying "it doesn't work" doesn't help, show us errors please.

**Comment by Aaalexer** [comment]
You already know about this, but, for everyone. When invokes ConnectAsync method, victoria throws `System.InvalidOperationException: _socketClient is not in ready state.` exception. Im using victoria 5.2.3, d.labs 3.0.3 and net 5

**Comment by AlexandreBazeaud** [comment]
Ok, i had the same issue using Victoria V6, Are you using DiscordShardedClient ?

**Comment by Aaalexer** [comment]
Yes

**Comment by AlexandreBazeaud** [comment]
Ok, so the problem come from  LavaNode.cs and has been resolved in 6.0 with this commit, https://github.com/Yucked/Victoria/commit/2c5be19c56e0a29663fc76e15159b1dc0e603b74
problem come from _socketClient`?`.CurrentUser which does black magic and think for some reason that CurrentUser is null, probably somewhere a operator override. removing the `?` should fix the problem

**Comment by Aaalexer** [comment]
Im using nuget package, so i cant edit it. Problem in victoria, as i understand

**Comment by AlexandreBazeaud** [comment]
Yes i may push a fix if i have time, don't know how many time you need to wait to get a new version. If your project is kinda small you may want to consider using Victoria 6.0 as this version works.

**Comment by Aaalexer** [comment]
I will be very happy if you will push a fix

**Comment by AlexandreBazeaud** [comment]
you will not get the new nuget package isntantly if i do this so you need to either wait or use v6.0 for now.

**Comment by Aaalexer** [comment]
Okay, thx for help
