### ISSUE TITLE
[ BUG ] KeyNotFoundException in LavaNode.cs

### ISSUE THREAD

**Issue by Matusson** [Yucked/Victoria#92]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

After connection and authorization are complete, the connection is constantly being closed and reopened again with code 1006, with no provided reason. The issue is consistently reproducible, may have occasionally happened before 5.2.0 but after upgrading it happens every time in my setup.

When using Log event, following error is displayed:
`System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.`
Seems to happen in LavaNode.cs line 457:
`                    var position = stateElement.GetProperty("position").GetInt64();`
I'm using the v5 branch updated to current state, with Discord.NET 2.4.0 and dev version of LavaLink (from 20.04.2021).

### `Stacktrace / Screenshots`

Error received in Log event:
```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Victoria.LavaNode`1.DataAsyncAsync(Byte[] data) in C:\Users\USER\Desktop\Victoria-5\src\LavaNode.cs:line 457
   at Victoria.LavaSocket.ReceiveAsync() in C:\Users\USER\Desktop\Victoria-5\src\LavaSocket.cs:line 202
```
Top of call stack:
![image](https://user-images.githubusercontent.com/41548922/127904270-f78b5a5f-f157-4ff7-9693-798fe855454d.png)
Bottom:
![image](https://user-images.githubusercontent.com/41548922/127904313-a6cbe5e6-9e91-4194-a9ee-7c023e0e1883.png)
Locals window when debugging line 457:
![image](https://user-images.githubusercontent.com/41548922/127904635-42ffa6ee-567b-453b-a36a-58207fc61b50.png)

**Comment by Matusson** [comment]
Update, the issue only seems to happen on LavaLink builds from the dev branch (available on the CI server). I was using build 1233, also tested 1236 and 1242, and ran into the same issue. Build 1232 (from the master branch) seems to work perfectly.
Looks like the dev branch has some breaking changes, I'm assuming I'll have to wait until dev is merged to master for Victoria to support it?

**Comment by Yucked** [comment]
I checked the master & dev branches for any changes to IMPLEMENTATION.md and the incoming message for `playerUpdate` hasn't changed.

https://github.com/freyacodes/Lavalink/blob/dev/IMPLEMENTATION.md#incoming-messages
https://github.com/freyacodes/Lavalink/blob/master/IMPLEMENTATION.md#incoming-messages

The key exists in both messages yet the exception thrown claims it isn't there. Regardless, commit 3c4e35adaac453dd0d5c2f1527ebae63e0f2fcd9 safely checks whether the mentioned key(s) exist in the `state` object before passing them on to `LavaPlayer`.

**Comment by Yucked** [comment]
Closing this issue. If the issue persist, feel free to reopen it and report your findings.
