### ISSUE TITLE
DefaultQueue modification

### ISSUE THREAD

**Issue by Aaalexer** [Yucked/Victoria#94]
I will be very happy if author add's a new method, to DefaultQueue, which add's an LavaTrack on first place in Queue. I know that DefaultQueue works on LinkedList<T> and it will be easy(i think).

**Comment by Yucked** [comment]
Commit 9a9648fc6cc5e0ea6b5b7b65dc39ad2492107015 addresses that feature request.
```cs
public class MyQueue < T >: DefaultQueue < T > where T: LavaTrack {
  public void EnqueueFirst(T item) {
    if (item == null) {
      throw new ArgumentNullException(nameof(item));
    }

    List.AddFirst(item);
  }
}
```
