### ISSUE TITLE
[ BUG ]

### ISSUE THREAD

**Issue by dvub** [Yucked/Victoria#95]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

Basically, if you play the same track twice with LavaLink, or have a song identical to the song that is playing in the queue, and you skip to it, the player completely shuts down with error code 1006. Same issue with the OnTrackEnded event and you use it to loop a song.

![image](https://user-images.githubusercontent.com/84478450/130676164-958363d6-7cba-4806-8b06-0b34630c932c.png)

**Comment by Yucked** [comment]
That was solved in recent commits and should no longer happen on 5.2.2. Feedback still appreciated.
